"""Canonical application error codes."""

from __future__ import annotations


class ErrorCode:
    """Shared error code constants for application and CLI layers."""

    CAPABILITY_NOT_FOUND = "CAPABILITY_NOT_FOUND"
    CAPABILITY_DISABLED = "CAPABILITY_DISABLED"
    CAPABILITY_NOT_SUPPORTED = "CAPABILITY_NOT_SUPPORTED"

    PROVIDER_NOT_FOUND = "PROVIDER_NOT_FOUND"
    PROVIDER_DISABLED = "PROVIDER_DISABLED"
    PROVIDER_NOT_CONFIGURED = "PROVIDER_NOT_CONFIGURED"
    PROVIDER_GENERATION_FAILED = "PROVIDER_GENERATION_FAILED"

    ENGINE_NOT_READY = "ENGINE_NOT_READY"
    ENGINE_RUN_FAILED = "ENGINE_RUN_FAILED"

    DOMAIN_VALIDATION_ERROR = "DOMAIN_VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
